name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pip install poetry==1.1.8 poetry-core==1.0.4
        shell: bash

      - name: Install dependencies
        run: poetry install
        shell: bash

      - name: Test with pytest
        run: poetry run pytest
        shell: bash
